// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Dashboard from "./Dashboard.res.mjs";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

function App(props) {
  React.useState(() => 0);
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx("div", {
      children: JsxRuntime.jsx(Dashboard.make, {}),
      className: "flex justify-evenly items-center"
    }),
    className: "max-w-300 mx-auto mt-12"
  });
}

let make = App;

export {
  make,
}
/*  Not a pure module */
