// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Chart(props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx("p", {
      children: "Chart Component",
      className: "text-white text-center"
    }),
    className: "w-full h-64 bg-slate-800 rounded-lg p-4"
  });
}

let make = Chart;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
