// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

async function fetchCrypto(coins) {
  let url = "https://api.coingecko.com/api/v3/simple/price?ids=" + coins + "&vs_currencies=usd";
  let res = await fetch(url, {});
  let result = await res.json();
  console.log(JSON.stringify(result));
  return result;
}

function Dashboard(props) {
  let match = React.useState(() => []);
  let setCryptos = match[1];
  let match$1 = React.useState(() => true);
  let setLoading = match$1[1];
  React.useEffect(() => {
    let getData = async () => {
      try {
        let json = await fetchCrypto("bitcoin,ethereum,cardano");
        let data = Belt_Option.getExn(Js_json.decodeObject(json));
        let getPrice = coin => Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(Belt_Option.flatMap(Js_dict.get(data, coin), Js_json.decodeObject), obj => Js_dict.get(obj, "usd")), Js_json.decodeNumber), 0.0);
        let cryptoList = [
          {
            id: "bitcoin",
            name: "Bitcoin",
            symbol: "BTC",
            image: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
            price: getPrice("bitcoin")
          },
          {
            id: "ethereum",
            name: "Ethereum",
            symbol: "ETH",
            image: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
            price: getPrice("ethereum")
          },
          {
            id: "cardano",
            name: "Cardano",
            symbol: "ADA",
            image: "https://assets.coingecko.com/coins/images/975/large/cardano.png",
            price: getPrice("cardano")
          }
        ];
        setCryptos(param => cryptoList);
        return setLoading(param => false);
      } catch (exn) {
        return setLoading(param => false);
      }
    };
    getData();
  }, []);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "💰 Crypto Dashboard",
        className: "text-4xl font-bold text-white mb-8"
      }),
      match$1[0] ? JsxRuntime.jsx("p", {
          children: "Chargement des données...",
          className: "text-white text-xl"
        }) : JsxRuntime.jsx("div", {
          children: match[0].map(c => JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("img", {
                    className: "w-12 h-12",
                    alt: c.name,
                    src: c.image
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h3", {
                        children: c.name,
                        className: "text-white text-xl font-bold"
                      }),
                      JsxRuntime.jsx("p", {
                        children: c.symbol,
                        className: "text-slate-400"
                      })
                    ]
                  })
                ],
                className: "flex items-center gap-4 mb-4"
              }),
              JsxRuntime.jsx("p", {
                children: "Prix actuel",
                className: "text-slate-400 text-sm"
              }),
              JsxRuntime.jsx("p", {
                children: "$" + c.price.toString(),
                className: "text-3xl font-bold text-cyan-400"
              })
            ],
            className: "bg-slate-800 rounded-lg p-6 shadow"
          }, c.id)),
          className: "grid grid-cols-1 md:grid-cols-3 gap-6"
        })
    ],
    className: "p-6 bg-slate-900 min-h-screen"
  });
}

let make = Dashboard;

export {
  fetchCrypto,
  make,
}
/* react Not a pure module */
