// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as JsxRuntime from "react/jsx-runtime";
import BitcoinPng from "./assets/image/bitcoin.png";

let bitcoinImg = BitcoinPng;

async function fetchCrypto(ids) {
  let url = "https://api.coinlore.net/api/ticker/?id=" + ids.map(prim => prim.trim()).join(",");
  let res = await fetch(url, {});
  let result = await res.json();
  console.log(JSON.stringify(result));
  return result;
}

function Dashboard(props) {
  let match = React.useState(() => []);
  let setCryptos = match[1];
  let match$1 = React.useState(() => true);
  let setLoading = match$1[1];
  React.useEffect(() => {
    let getData = async () => {
      try {
        let json = await fetchCrypto([
          "90",
          "80",
          "257"
        ]);
        let dataArrayOpt = Js_json.decodeArray(json);
        if (dataArrayOpt !== undefined) {
          let cryptoList = Stdlib_Array.filterMap(dataArrayOpt, item => {
            let objOpt = Js_json.decodeObject(item);
            if (objOpt === undefined) {
              return;
            }
            let id = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(objOpt, "id"), Js_json.decodeString), "");
            let name = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(objOpt, "name"), Js_json.decodeString), "");
            let symbol = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(objOpt, "symbol"), Js_json.decodeString), "");
            let price = Belt_Option.getWithDefault(Belt_Option.flatMap(Belt_Option.flatMap(Js_dict.get(objOpt, "price_usd"), Js_json.decodeString), Stdlib_Float.fromString), 0.0);
            return {
              id: id,
              name: name,
              symbol: symbol,
              image: bitcoinImg,
              price: price
            };
          });
          setCryptos(param => cryptoList);
          return setLoading(param => false);
        }
        console.log("Erreur: pas un array");
        return setLoading(param => false);
      } catch (exn) {
        console.log("Erreur try/catch");
        return setLoading(param => false);
      }
    };
    getData();
  }, []);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "💰 Crypto Dashboard",
        className: "text-4xl font-bold text-white mb-8"
      }),
      match$1[0] ? JsxRuntime.jsx("p", {
          children: "Chargement des données...",
          className: "text-white text-xl"
        }) : JsxRuntime.jsx("div", {
          children: match[0].map(c => JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("img", {
                    className: "w-12 h-12",
                    alt: c.name,
                    src: c.image
                  }),
                  JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h3", {
                        children: c.name,
                        className: "text-white text-xl font-bold"
                      }),
                      JsxRuntime.jsx("p", {
                        children: c.symbol,
                        className: "text-slate-400"
                      })
                    ]
                  })
                ],
                className: "flex items-center gap-4 mb-4"
              }),
              JsxRuntime.jsx("p", {
                children: "Prix actuel",
                className: "text-slate-400 text-sm"
              }),
              JsxRuntime.jsx("p", {
                children: "$" + c.price.toString(),
                className: "text-3xl font-bold text-cyan-400"
              })
            ],
            className: "bg-slate-800 rounded-lg p-6 shadow"
          }, c.id)),
          className: "grid grid-cols-1 md:grid-cols-3 gap-6"
        })
    ],
    className: "p-6 bg-slate-900 min-h-screen"
  });
}

let make = Dashboard;

export {
  bitcoinImg,
  fetchCrypto,
  make,
}
/* bitcoinImg Not a pure module */
